name: Test Changelog Action

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Test changelog action
        uses: ./
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
